version: '3'
services:
  kafka-broker:
    image: confluentinc/cp-kafka:5.5.2
    container_name: kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-broker:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka-broker
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG4J_ROOT_LOGLEVEL=ERROR
      - KAFKA_LOG4J_LOGGERS=org.apache.zookeeper=ERROR,org.apache.kafka=ERROR,kafka=ERROR,kafka.cluster=ERROR,kafka.controller=ERROR,kafka.coordinator=ERROR,kafka.log=ERROR,kafka.server=ERROR,kafka.zookeeper=ERROR,state.change.logger=ERROR
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.2
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
  
  zookeeper-druid:
    image: confluentinc/cp-zookeeper:5.5.2
    container_name: zookeeper-druid
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  postgres:
    container_name: postgres
    image: postgres:13.3
    ports: 
      - "5432:5432"
    volumes:
      - metadata_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_MULTIPLE_DATABASES=druid,druid,druidpwd:dataflow,dataflow,dataflowpwd
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres

volumes:
    metadata_data: {}